1. Neural networks transform floating-point representations into other floatingpoint representations. The starting and ending representations are typically human interpretable, but the intermediate representations are less so.
2. These floating-point representations are stored in tensors.
3. Tensors are multidimensional arrays; they are the basic data structure in PyTorch.
4. PyTorch has a comprehensive standard library for tensor creation, manipulation, and mathematical operations.
5. Tensors can be serialized to disk and loaded back.
6. All tensor operations in PyTorch can execute on the CPU as well as on the GPU, with no change in the code.
7. PyTorch uses a trailing underscore to indicate that a function operates in place on a tensor (for example, Tensor.sqrt_).

In [2]:
import torch

In [9]:
# 1d array
a= torch.ones(5)
print(a)
print(type(a))
print(a[1])
print(float(a[1]))
# 2d tensor
b= torch.ones(2,3)
print(b)
print(b.shape)

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>
tensor(1.)
1.0
tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.Size([2, 3])


Python lists or tuples of numbers are collections of Python objects that are individually
allocated in memory. PyTorch tensors or NumPy
arrays, on the other hand, are views over (typically) contiguous memory blocks containing
unboxed C numeric types rather than Python objects. Each element is a 32-bit (4-byte)
float in this case. This means storing a 1D
tensor of 1,000,000 float numbers will require exactly 4,000,000 contiguous bytes, plus
a small overhead for the metadata (such as dimensions and numeric type).

In [20]:
# to represent a geometrical object, perhaps a 2D triangle with vertices at coordinates 
# (4, 1), (5, 3), and (2, 1).
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
# points[row , column] >> indexing
points, points.shape, points[2][1], points[1], points[1:2, ], points[:2, 1], points[:, 1]

(tensor([[4., 1.],
         [5., 3.],
         [2., 1.]]),
 torch.Size([3, 2]),
 tensor(1.),
 tensor([5., 3.]),
 tensor([[5., 3.]]),
 tensor([1., 3.]),
 tensor([1., 3., 1.]))

sometimes the RGB channels are in dimension 0, and sometimes they are in dimension 1 But we can generalize by counting from the end: they are always in dimension –3, the third from the end. The lazy, unweighted mean can thus be written as follows:

In [23]:
# shape [channels, rows, columns]
img_t = torch.randn(3, 5, 5)
img_t, img_t.shape

(tensor([[[-1.1906, -0.3990,  1.4663, -0.6403,  0.5060],
          [-0.5317, -0.3363, -0.6422,  1.0012,  0.2621],
          [ 1.9996,  1.5415, -0.4395, -0.6198, -0.2690],
          [ 0.0649, -0.3438, -0.1805,  0.1883,  0.0440],
          [ 0.0092, -1.2074,  0.7788, -1.4720,  0.1654]],
 
         [[-0.0265, -0.9291,  0.3678,  0.6406,  0.5012],
          [-0.0472,  0.3932,  0.7769, -0.1731,  0.4117],
          [-0.2803,  0.3134, -0.5682, -0.2266,  0.1150],
          [-0.3496,  0.6546, -2.0509,  1.4073, -0.3369],
          [ 0.2415, -0.3576, -0.4784, -0.8917,  0.9275]],
 
         [[-1.5339,  1.5665, -1.5221,  1.7443,  0.0858],
          [-0.1007,  0.7191, -0.2154, -0.1355,  0.0127],
          [ 0.1282, -0.5933,  1.1130,  1.0193, -1.4197],
          [ 0.8274, -1.6891,  0.1900, -0.7786, -0.7436],
          [-0.8988, -1.1767,  0.4368,  1.4466, -0.2988]]]),
 torch.Size([3, 5, 5]))

In [32]:
# finding mean across columns
print(img_t.mean(-1))
# finding mean across rows
print(img_t.mean(-2))
# finding mean across channels
img_gray_naive = img_t.mean(-3)
img_gray_naive

tensor([[-0.0515, -0.0494,  0.4426, -0.0454, -0.3452],
        [ 0.1108,  0.2723, -0.1293, -0.1351, -0.1118],
        [ 0.0681,  0.0561,  0.0495, -0.4388, -0.0982]])
tensor([[ 7.0284e-02, -1.4899e-01,  1.9660e-01, -3.0853e-01,  1.4172e-01],
        [-9.2398e-02,  1.4908e-02, -3.9057e-01,  1.5130e-01,  3.2370e-01],
        [-3.1554e-01, -2.3470e-01,  4.5768e-04,  6.5920e-01, -4.7273e-01]])


tensor([[-0.9170,  0.0795,  0.1040,  0.5815,  0.3643],
        [-0.2265,  0.2587, -0.0269,  0.2309,  0.2289],
        [ 0.6158,  0.4206,  0.0351,  0.0576, -0.5246],
        [ 0.1809, -0.4594, -0.6805,  0.2723, -0.3455],
        [-0.2160, -0.9139,  0.2457, -0.3057,  0.2647]])

In [24]:
# shape [batch, channels, rows, columns]
batch_t = torch.randn(2, 3, 5, 5)
batch_t, batch_t.shape

(tensor([[[[ 1.4061, -0.8478,  0.6290,  1.3703,  1.2419],
           [-0.8682, -0.3843,  0.1393, -1.3313,  0.1641],
           [ 0.0292,  0.9762, -1.3640, -0.5952, -0.2424],
           [ 0.9331,  0.2788, -1.1940, -0.3628,  0.8974],
           [-0.0238,  1.9626,  0.1784, -0.0919, -0.2715]],
 
          [[-0.4081,  0.4525,  1.2643,  1.1695, -0.7364],
           [-0.3409,  1.8004, -0.8791,  1.7764, -0.0799],
           [ 0.7354,  0.5276,  0.6712,  0.7413,  0.1751],
           [ 0.0580,  0.2251,  0.8568,  0.3369,  1.4278],
           [ 1.2966,  0.8079,  2.0605, -0.7384,  0.3959]],
 
          [[ 0.4270, -0.0847, -0.5829, -0.0885,  0.6286],
           [ 0.9648,  1.3463, -0.4546, -0.2526,  1.0077],
           [ 0.4707,  0.3930,  0.9050, -0.8490,  0.8095],
           [-0.2637,  0.1342,  0.0719,  1.3535,  0.9777],
           [-0.6472,  0.1750,  0.6022, -1.0849, -0.5681]]],
 
 
         [[[-1.5502, -0.8889,  0.6502,  0.5591,  2.7198],
           [-0.6045, -1.1649,  0.4860,  0.4917,  1.1709],
  

In [26]:
# batch wise mean is computed as
batch_gray_naive = batch_t.mean(-3)
batch_gray_naive, batch_gray_naive.shape

(tensor([[[ 0.4750, -0.1600,  0.4368,  0.8171,  0.3780],
          [-0.0814,  0.9208, -0.3981,  0.0642,  0.3639],
          [ 0.4118,  0.6323,  0.0707, -0.2343,  0.2474],
          [ 0.2425,  0.2127, -0.0884,  0.4426,  1.1010],
          [ 0.2085,  0.9818,  0.9471, -0.6384, -0.1479]],
 
         [[-0.1196, -0.8563, -0.1624,  1.2097,  1.1671],
          [-0.5144, -0.5795,  1.2142,  0.1995,  0.0600],
          [-0.0501,  0.5402,  0.9044, -0.6693, -0.4334],
          [-0.1078, -0.7747,  0.0516,  0.4820, -0.7620],
          [-0.8701,  0.5495,  1.0318,  0.0410,  0.0740]]]),
 torch.Size([2, 5, 5]))

In [33]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])
img_t, weights

(tensor([[[-1.1906, -0.3990,  1.4663, -0.6403,  0.5060],
          [-0.5317, -0.3363, -0.6422,  1.0012,  0.2621],
          [ 1.9996,  1.5415, -0.4395, -0.6198, -0.2690],
          [ 0.0649, -0.3438, -0.1805,  0.1883,  0.0440],
          [ 0.0092, -1.2074,  0.7788, -1.4720,  0.1654]],
 
         [[-0.0265, -0.9291,  0.3678,  0.6406,  0.5012],
          [-0.0472,  0.3932,  0.7769, -0.1731,  0.4117],
          [-0.2803,  0.3134, -0.5682, -0.2266,  0.1150],
          [-0.3496,  0.6546, -2.0509,  1.4073, -0.3369],
          [ 0.2415, -0.3576, -0.4784, -0.8917,  0.9275]],
 
         [[-1.5339,  1.5665, -1.5221,  1.7443,  0.0858],
          [-0.1007,  0.7191, -0.2154, -0.1355,  0.0127],
          [ 0.1282, -0.5933,  1.1130,  1.0193, -1.4197],
          [ 0.8274, -1.6891,  0.1900, -0.7786, -0.7436],
          [-0.8988, -1.1767,  0.4368,  1.4466, -0.2988]]]),
 tensor([0.2126, 0.7152, 0.0722]))

In [37]:
unsqueezed_weights= weights.unsqueeze(-1).unsqueeze(-1)
unsqueezed_weights, unsqueezed_weights.shape

(tensor([[[0.2126]],
 
         [[0.7152]],
 
         [[0.0722]]]), torch.Size([3, 1, 1]))

In [40]:
img_weights = (img_t * unsqueezed_weights)
img_weights, img_weights.shape, img_weights.sum(-3)

(tensor([[[-2.5312e-01, -8.4829e-02,  3.1173e-01, -1.3612e-01,  1.0757e-01],
          [-1.1303e-01, -7.1490e-02, -1.3652e-01,  2.1285e-01,  5.5733e-02],
          [ 4.2511e-01,  3.2773e-01, -9.3430e-02, -1.3178e-01, -5.7196e-02],
          [ 1.3795e-02, -7.3095e-02, -3.8365e-02,  4.0028e-02,  9.3645e-03],
          [ 1.9521e-03, -2.5670e-01,  1.6558e-01, -3.1295e-01,  3.5174e-02]],
 
         [[-1.8934e-02, -6.6450e-01,  2.6308e-01,  4.5815e-01,  3.5847e-01],
          [-3.3734e-02,  2.8120e-01,  5.5563e-01, -1.2381e-01,  2.9446e-01],
          [-2.0049e-01,  2.2418e-01, -4.0639e-01, -1.6204e-01,  8.2217e-02],
          [-2.5000e-01,  4.6819e-01, -1.4668e+00,  1.0065e+00, -2.4093e-01],
          [ 1.7275e-01, -2.5576e-01, -3.4218e-01, -6.3777e-01,  6.6333e-01]],
 
         [[-1.1075e-01,  1.1310e-01, -1.0990e-01,  1.2594e-01,  6.1943e-03],
          [-7.2680e-03,  5.1916e-02, -1.5551e-02, -9.7826e-03,  9.2023e-04],
          [ 9.2594e-03, -4.2833e-02,  8.0359e-02,  7.3592e-02, -1.0250

In [41]:
batch_weights = (batch_t * unsqueezed_weights)
batch_weights, batch_weights.shape, batch_weights.sum(-3)

(tensor([[[[ 2.9893e-01, -1.8024e-01,  1.3373e-01,  2.9133e-01,  2.6403e-01],
           [-1.8459e-01, -8.1708e-02,  2.9609e-02, -2.8302e-01,  3.4878e-02],
           [ 6.2100e-03,  2.0755e-01, -2.8999e-01, -1.2654e-01, -5.1539e-02],
           [ 1.9839e-01,  5.9275e-02, -2.5384e-01, -7.7133e-02,  1.9078e-01],
           [-5.0619e-03,  4.1724e-01,  3.7934e-02, -1.9530e-02, -5.7716e-02]],
 
          [[-2.9191e-01,  3.2360e-01,  9.0426e-01,  8.3644e-01, -5.2670e-01],
           [-2.4381e-01,  1.2876e+00, -6.2877e-01,  1.2705e+00, -5.7168e-02],
           [ 5.2599e-01,  3.7737e-01,  4.8001e-01,  5.3016e-01,  1.2523e-01],
           [ 4.1488e-02,  1.6096e-01,  6.1281e-01,  2.4098e-01,  1.0211e+00],
           [ 9.2734e-01,  5.7779e-01,  1.4737e+00, -5.2809e-01,  2.8316e-01]],
 
          [[ 3.0831e-02, -6.1126e-03, -4.2083e-02, -6.3915e-03,  4.5383e-02],
           [ 6.9660e-02,  9.7199e-02, -3.2819e-02, -1.8239e-02,  7.2754e-02],
           [ 3.3986e-02,  2.8377e-02,  6.5344e-02, -6.1300

**Python objects**
1. Numbers in Python are objects. Whereas a floating-point number might require only, for instance, 32 bits to be represented on a computer, Python will convert it into a full-fledged Python object with reference counting, and so on. This operation, called boxing, is not a problem if we need to store a small number of numbers, but allocating millions gets very inefficient.
2. Lists in Python are meant for sequential collections of objects. There are no operations defined for, say, efficiently taking the dot product of two vectors, or summing vectors together. Also, Python lists have no way of optimizing the layout of their contents in memory, as they are indexable collections of pointers to Python objects (of any kind, not just numbers). Finally, Python lists are one-dimensional, and although we can create lists of lists, this is again very inefficient.
3. The Python interpreter is slow compared to optimized, compiled code. Performing mathematical operations on large collections of numerical data can be much faster using optimized code written in a compiled, low-level language like C.

For these reasons, data science libraries rely on NumPy or introduce dedicated data
structures like PyTorch tensors, which provide efficient low-level implementations of
numerical data structures and related operations on them, wrapped in a convenient
high-level API.

***torch.transpose(input, dim0, dim1) → Tensor***
Returns a tensor that is a transposed version of input. The given dimensions dim0 and dim1 are swapped

In [2]:
a = torch.ones(3, 2)
print(a)
a_t = torch.transpose(a, 0, 1)
a_t

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [5]:
# or
a_t = a.transpose(0, 1)
a_t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

**Tensors: Scenic views of storage**
Values in
tensors are allocated in contiguous chunks of memory managed by torch.Storage
instances. A storage is a one-dimensional array of numerical data: that is, a contiguous
block of memory containing numbers of a given type, such as float (32 bits representing
a floating-point number) or int64 (64 bits representing an integer).

Even though the tensor reports itself as having three rows and two columns, the storage
under the hood is a contiguous array of size 6. In this sense, the tensor just knows
how to translate a pair of indices into a location in the storage.

We can’t index a storage of a 2D tensor using two indices. The layout of a storage is
always one-dimensional, regardless of the dimensionality of any and all tensors that
might refer to it

In [6]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
print(points[1])
points.storage()

tensor([5., 3.])


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [4]:
points_storage = points.storage()
points_storage[3]
# or points.storage[3]

3.0

In [7]:
# We can’t index a storage of a 2D tensor using two indices. The layout of a storage is always one-dimensional, regardless of the dimensionality of any and all tensors that might refer to it
points.storage[0][0]

TypeError: 'builtin_function_or_method' object is not subscriptable

**Modifying stored values: In-place operations** <br>
zero_, which indicates that the
method operates in place by modifying the input instead of creating a new output tensor
and returning it. For instance, the zero_ method zeros out all the elements of the input.
Any method without the trailing underscore leaves the source tensor unchanged and
instead returns a new tensor:

In [8]:
a=torch.ones(3,2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [12]:
a.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

**Tensor metadata: Size, offset, and stride**<br>
1. The size (or shape, in NumPy parlance) is a tuple indicating how many elements across each dimension the tensor represents. It’s important to note that this is the same information contained in the shape property of tensor objects:
2. The storage offset is the index in the storage corresponding to the first element in the tensor.
3. The stride is the number of elements in the storage that need to be skipped over to obtain the next element along each dimension.
4. Accessing an element i, j in a 2D tensor results in accessing the storage_offset + stride[0] * i + stride[1] * j element in the storage. The offset will usually be zero; if this tensor is a view of a storage created to hold a larger tensor, the offset might be a positive value


In [6]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
print(points[1], points.shape, points.size(), points.stride())
second_point = points[1]
second_point.storage_offset()

tensor([5., 3.]) torch.Size([3, 2]) torch.Size([3, 2]) (2, 1)


2

**Transposing**<br>
This tells us that increasing the first index by one in points—for example, going from
points[0,0] to points[1,0]—will skip along the storage by two elements, while increasing
the second index—from points[0,0] to points[0,1]—will skip along the storage by
one. In other words, the storage holds the elements in the tensor sequentially row by row.<br>
**Transposing in higher dimensions**<br>
We can transpose a multidimensional array by specifying the two dimensions along which transposing
(flipping shape and stride) should occur:  


In [7]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [8]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [9]:
id(points.storage()) == id(points_t.storage())

False

In [10]:
points.stride(), points_t.stride()

((2, 1), (1, 2))

In [20]:
some_t = torch.randn(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape, transpose_t.shape

(torch.Size([3, 4, 5]), torch.Size([5, 4, 3]))

In [21]:
some_t, transpose_t

(tensor([[[ 0.0326, -1.3739,  0.6134,  0.5517, -0.0641],
          [ 0.2173, -1.0482,  0.1910, -1.4370,  1.4592],
          [-1.4582,  0.6801,  1.2730, -0.2057,  0.6537],
          [-0.8117,  0.3929,  0.0356,  1.1638,  0.8348]],
 
         [[ 1.0885,  1.4824, -0.0166,  1.0396, -0.4837],
          [ 0.2324,  0.2062, -0.4196,  0.5573, -0.4953],
          [ 0.5752, -2.7219,  0.0399,  0.7238, -1.3694],
          [ 0.5891,  0.6332, -1.2489,  1.7633,  0.4609]],
 
         [[ 0.2144,  0.8151, -0.1596, -1.6279,  1.6376],
          [-0.5642, -1.2167, -1.9270, -0.9142, -0.5977],
          [ 0.2281, -2.2899,  0.6417, -0.9800, -0.5992],
          [ 1.2387,  1.0144,  0.5934, -0.2347, -0.3119]]]),
 tensor([[[ 0.0326,  1.0885,  0.2144],
          [ 0.2173,  0.2324, -0.5642],
          [-1.4582,  0.5752,  0.2281],
          [-0.8117,  0.5891,  1.2387]],
 
         [[-1.3739,  1.4824,  0.8151],
          [-1.0482,  0.2062, -1.2167],
          [ 0.6801, -2.7219, -2.2899],
          [ 0.3929,  0.6332,  1

**Moving tensors to the GPU**
1. PyTorch tensors also can be stored on a different kind of processor: a graphics processing unit (GPU). Every PyTorch tensor can be transferred to (one of) the GPU(s) in order to perform massively parallel, fast computations.
2. a PyTorch Tensor also has the notion of device, which is where on the computer the tensor data is placed.
3. Doing so returns a new tensor that has the same numerical data, but stored in the RAM of the GPU, rather than in regular system RAM. Now that the data is stored locally on the GPU, we’ll start to see the speedups mentioned earlier when performing mathematical operations on the tensor. In almost all cases, CPU- and GPU-based tensors expose the same user-facing API, making it much easier to write code that is agnostic to where, exactly, the heavy number crunching is running.
4. If our machine has more than one GPU, we can also decide on which GPU we allocate the tensor by passing a zero-based integer identifying the GPU on the machine,

In [24]:
# error because i'm executing the codes on a CPU 
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

AssertionError: Torch not compiled with CUDA enabled

In [23]:
# We could instead copy a tensor created on the CPU onto the GPU using the to method:
points_gpu = points.to(device='cuda')

AssertionError: Torch not compiled with CUDA enabled

In [25]:
points_gpu = points.to(device='cuda:0')

AssertionError: Torch not compiled with CUDA enabled

**Serializing tensors- saving data to file**<br>
Creating a tensor on the fly is all well and good, but if the data inside is valuable, we will
want to save it to a file and load it back at some point. After all, we don’t want to have
to retrain a model from scratch every time we start running our program!
PyTorch uses **pickle** under the hood to serialize the tensor object, plus dedicated serialization code
for the storage. Here’s how we can save our points tensor to an ourpoints.t file.<br><br>
While we can quickly save tensors this way if we only want to load them with PyTorch,
the file format itself is not interoperable: we can’t read the tensor with software other
than PyTorch. Depending on the use case, this may or may not be a limitation, but we
should learn how to save tensors interoperably for those times when it is.<br><br>
**Serializing to HDF5 with h5py**<br>
HDF5 is a portable, widely supported
format for representing serialized multidimensional arrays, organized in a nested keyvalue
dictionary. Python supports HDF5 through the h5py library (www.h5py.org),
which accepts and returns data in the form of NumPy arrays.


In [28]:
print(points)
torch.save(points, 'D:/Research/Pytorch/points.t')
# As an alternative, we can pass a file descriptor in lieu of the filename
# with open('D:/Research/Pytorch/points.t','wb') as f:
#     torch.save(points, f)
# Loading our points back is similarly a one-liner
points = torch.load('D:/Research/Pytorch/points.t')
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])


tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [39]:
# $ conda install h5py
import h5py
print(points)
f = h5py.File('D:/Research/Pytorch/points.hdf5', 'w')
dset = f.create_dataset('key_name', data=points.numpy())
f.close()

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])


In [33]:
# Here 'coords' is a key into the HDF5 file. We can have other keys—even nested ones.
# One of the interesting things in HDF5 is that we can index the dataset while on disk
# and access only the elements we’re interested in. Let’s suppose we want to load just
# the last two points in our dataset:


In [42]:
f = h5py.File('D:/Research/Pytorch/points.hdf5', 'r')
k=f['key_name']
last_points=k[-1]
print(last_points, type(last_points))
# convert last_points to torch data type
last_points = torch.from_numpy(last_points)
print(last_points, type(last_points))
f.close()

[2. 1.] <class 'numpy.ndarray'>
tensor([2., 1.]) <class 'torch.Tensor'>
